version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python src/train.py --model-path model/model.joblib
artifacts:
  files:
    - model/model.joblib